language: ruby
rvm:
- 2.3.1
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 2
before_script:
- bundle exec rake db:create:all
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
script:
- bundle exec rake spec
# - bundle exec rake cucumber