language: ruby
rvm:
- 2.3.1
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 2
before_script:
- bundle exec  rails db:create:all
- bundle exec  rails db:migrate
- bundle exec  rails db:test:prepare
script:
- bundle exec rake spec
# - bundle exec rake cucumber
 sudo: 
 - required  